version: '3.7'

services:
    db:
        image: mysql:8.0.17
        env_file: ./.env.dev
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_HOST=${DJANGO_DB_HOST}
            - MYSQL_USER=${DJANGO_DB_USER}
            - MYSQL_PASSWORD=${DJANGO_DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DJANGO_DB_PASSWORD}
            - MYSQL_DATABASE=${DJANGO_DB_NAME}
        volumes:
            - ./tmp/db:/var/lib/mysql        
    web:
        env_file: ./.env.dev
        build: .
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        depends_on: 
            - db