version: '3'

services:
  db:
    image: mysql:5.7
    env_file: ./.env
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_HOST=${DJANGO_DB_HOST}
      - MYSQL_USER=${DJANGO_DB_USER}
      - MYSQL_PASSWORD=${DJANGO_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DJANGO_DB_PASSWORD}
      - MYSQL_DATABASE=${DJANGO_DB_NAME}
  web:
    env_file: ./.env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/core
    ports:
      - "8000:8000"
    depends_on: 
      - db